title: "Privacy Notice"
navbar-col: "#0000"
navbar-text-col: "#0000"
navbar-border-col: "#0000"
page-col: "#0000"
text-col: "#0000"
link-col: "#0000"
hover-col: "#0000"
footer-col: "#0000"
footer-text-col: "#0000"
footer-link-col: "#0000"
footer-hover-col: "#0000"
